#! /usr/bin/python
"""
    LOCALIZER: subcellular localization prediction of plant  
    and effector proteins in the plant cell
    Copyright (C) 2016-2017 Jana Sperschneider	

    This program is free software; you can redistribute it and/or modify  
    it under the terms of the GNU General Public License as published by  
    the Free Software Foundation; either version 3 of the License, or     
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    Please also see the CSIRO Disclaimer provided with LOCALIZER (LICENCE.txt).

    Contact: jana.sperschneider@csiro.au
"""
# -----------------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------------
WINDOW_SIZE = [x for x in xrange(40, 100, 10)] 
WINDOW_SIZE_CLEAVAGE = [x for x in xrange(20, 100, 1)] 
STEP_SIZE = 1
# -----------------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------------
ARFF_CHLOROPLAST_HEADER = '''@RELATION effectors
@ATTRIBUTE Charge NUMERIC
@ATTRIBUTE Isoelectric NUMERIC
@ATTRIBUTE Tiny NUMERIC
@ATTRIBUTE Small NUMERIC
@ATTRIBUTE Aliphatic NUMERIC
@ATTRIBUTE Aromatic NUMERIC
@ATTRIBUTE Nonpolar NUMERIC
@ATTRIBUTE Polar NUMERIC
@ATTRIBUTE Charged NUMERIC
@ATTRIBUTE Basic NUMERIC
@ATTRIBUTE Acidic NUMERIC
@ATTRIBUTE A NUMERIC
@ATTRIBUTE C NUMERIC
@ATTRIBUTE D NUMERIC
@ATTRIBUTE E NUMERIC
@ATTRIBUTE F NUMERIC
@ATTRIBUTE G NUMERIC
@ATTRIBUTE H NUMERIC
@ATTRIBUTE I NUMERIC
@ATTRIBUTE K NUMERIC
@ATTRIBUTE L NUMERIC
@ATTRIBUTE M NUMERIC
@ATTRIBUTE N NUMERIC
@ATTRIBUTE P NUMERIC
@ATTRIBUTE Q NUMERIC
@ATTRIBUTE R NUMERIC
@ATTRIBUTE S NUMERIC
@ATTRIBUTE T NUMERIC
@ATTRIBUTE V NUMERIC
@ATTRIBUTE W NUMERIC
@ATTRIBUTE Y NUMERIC
@ATTRIBUTE Gravy NUMERIC
@ATTRIBUTE Helix NUMERIC
@ATTRIBUTE Turn NUMERIC
@ATTRIBUTE Sheet NUMERIC
@ATTRIBUTE aromaticity NUMERIC
@ATTRIBUTE Charge_short NUMERIC
@ATTRIBUTE Isoelectric_short NUMERIC
@ATTRIBUTE A_short NUMERIC
@ATTRIBUTE C_short NUMERIC
@ATTRIBUTE D_short NUMERIC
@ATTRIBUTE E_short NUMERIC
@ATTRIBUTE F_short NUMERIC
@ATTRIBUTE G_short NUMERIC
@ATTRIBUTE H_short NUMERIC
@ATTRIBUTE I_short NUMERIC
@ATTRIBUTE K_short NUMERIC
@ATTRIBUTE L_short NUMERIC
@ATTRIBUTE M_short NUMERIC
@ATTRIBUTE N_short NUMERIC
@ATTRIBUTE P_short NUMERIC
@ATTRIBUTE Q_short NUMERIC
@ATTRIBUTE R_short NUMERIC
@ATTRIBUTE S_short NUMERIC
@ATTRIBUTE T_short NUMERIC
@ATTRIBUTE V_short NUMERIC
@ATTRIBUTE W_short NUMERIC
@ATTRIBUTE Y_short NUMERIC
@ATTRIBUTE class {CHLOROPLAST,NON_CHLOROPLAST}
@DATA
'''
# -----------------------------------------------------------------------------------------------------------
ARFF_MITOCHONDRIA_HEADER = '''@RELATION effectors
@ATTRIBUTE Charge NUMERIC
@ATTRIBUTE Isoelectric NUMERIC
@ATTRIBUTE Tiny NUMERIC
@ATTRIBUTE Small NUMERIC
@ATTRIBUTE Aliphatic NUMERIC
@ATTRIBUTE Aromatic NUMERIC
@ATTRIBUTE Nonpolar NUMERIC
@ATTRIBUTE Polar NUMERIC
@ATTRIBUTE Charged NUMERIC
@ATTRIBUTE Basic NUMERIC
@ATTRIBUTE Acidic NUMERIC
@ATTRIBUTE A NUMERIC
@ATTRIBUTE C NUMERIC
@ATTRIBUTE D NUMERIC
@ATTRIBUTE E NUMERIC
@ATTRIBUTE F NUMERIC
@ATTRIBUTE G NUMERIC
@ATTRIBUTE H NUMERIC
@ATTRIBUTE I NUMERIC
@ATTRIBUTE K NUMERIC
@ATTRIBUTE L NUMERIC
@ATTRIBUTE M NUMERIC
@ATTRIBUTE N NUMERIC
@ATTRIBUTE P NUMERIC
@ATTRIBUTE Q NUMERIC
@ATTRIBUTE R NUMERIC
@ATTRIBUTE S NUMERIC
@ATTRIBUTE T NUMERIC
@ATTRIBUTE V NUMERIC
@ATTRIBUTE W NUMERIC
@ATTRIBUTE Y NUMERIC
@ATTRIBUTE Gravy NUMERIC
@ATTRIBUTE Helix NUMERIC
@ATTRIBUTE Turn NUMERIC
@ATTRIBUTE Sheet NUMERIC
@ATTRIBUTE aromaticity NUMERIC
@ATTRIBUTE Charge_short NUMERIC
@ATTRIBUTE Isoelectric_short NUMERIC
@ATTRIBUTE A_short NUMERIC
@ATTRIBUTE C_short NUMERIC
@ATTRIBUTE D_short NUMERIC
@ATTRIBUTE E_short NUMERIC
@ATTRIBUTE F_short NUMERIC
@ATTRIBUTE G_short NUMERIC
@ATTRIBUTE H_short NUMERIC
@ATTRIBUTE I_short NUMERIC
@ATTRIBUTE K_short NUMERIC
@ATTRIBUTE L_short NUMERIC
@ATTRIBUTE M_short NUMERIC
@ATTRIBUTE N_short NUMERIC
@ATTRIBUTE P_short NUMERIC
@ATTRIBUTE Q_short NUMERIC
@ATTRIBUTE R_short NUMERIC
@ATTRIBUTE S_short NUMERIC
@ATTRIBUTE T_short NUMERIC
@ATTRIBUTE V_short NUMERIC
@ATTRIBUTE W_short NUMERIC
@ATTRIBUTE Y_short NUMERIC
@ATTRIBUTE class {MITOCHONDRIA,NON_MITOCHONDRIA}
@DATA
'''
# -----------------------------------------------------------------------------------------------------------
NLS_MOTIFS = ['KR[KR]R', 'K[KR]RK', '[PR]..KR[^DE][KR]', 'KR.[WFY]..AF', '[RP]..KR[KR][^DE]', 'LGKR[KR][WFY]', 
'KR...........K[KR][KR]', 'KR............K[KR][KR]', 'KR.............K[KR][KR]', 'KR...........K[KR].[KR]',
'KR............K[KR].[KR]', 'KR.............K[KR].[KR]', 'AAAED', 'AEKSKKK', 'AHFKISGEKRPSTDPGKKAKNPKKKKKKDP', 'AHRAKKMSKTHA', 'AKFGAENVARRVAFRKS', 'AKKRKK', 'AKKTK', 'AKREAALE', 'AKRMAQEA', 'AKRNTRTY', 'AKRTNVPG', 'ASEEEEEQLENGKHIKKFKR', 'ASIERKRQRALMLRQARLAARP', 'ATKARRTI', 'CKRHGVNR', 'CPFPGCGKIFARSENLKIHKRTH', 'CTKRPRW', 'CYWEECPREGKSFKAKYKLVNHIRVH', 'DKAKRVSRNKSEKKRR', 'DKALKKRSGKKDKHSQSPRAAGPREG', 'DKKLGRPH', 'DKKRKTRK', 'DNFQDDPHAG', 'DQMLKRRNVS', 'EELRLKEELLKGIYA', 'EEQLRRRKNSRLNNTG', 'EKKFAYQA', 'EKKGLKLT', 'EKREAEWK', 'EKRSPTEK', 'EKRYGPCI', 'ELVEQILAL', 'EQLFKRRNVA', 'ERARAC', 'ERRRRKRRLR', 'FKRIKRKI', 'FKRR', 'FKVK', 'GAVVED', 'GGSRRKRRKDRDSGRK', 'GKKIADRAKMRGKAKVEKRGQEGGGAKGGKK', 'GKKYENVVIKRSPRKRGRPRKDGTS', 'GKRKRV', 'GKRSLEVT', 'GKVSKRKAV', 'GPRVRYNPYTTRPNRRGDTWHDRDRIHVTVRRDR', 'GRKVAKDS', 'GTPRKKIQYRVKSRTPS', 'HKKKHPDASVNFSEFSK', 'HRCVLAACSTYFKKLFK', 'HSERYKDD', 'IKKKKDP', 'IKKKQKH', 'IKRNFSDIASPA', 'IKRRPTLPQTPASAPQVLSPSPKRQ', 'IPDPTGQS', 'IRKDVDDL', 'IRKEESAL', 'IRRIYSDE', 'IRRPGRSR', 'IVINILSE', 'KAKRRLR', 'KAKTFALKALKKK', 'KALGVNMMMRK', 'KDKRIKPIDPKKKISR', 'KEKCKENGKMFKDK', 'KELRRKKLVKR', 'KFKIKPGPECGTADGRSKK', 'KGKRSKRSR', 'KGKSDEGKVRKVLK', 'KGPPR', 'KGPRAKVAKLNIQSLAPVKKKKMVTGALGTPADLAPVDVEFSFPKFSRLRRGLKAEAVKGPVPAAPARRRLQLPRLRVR', 'KGPRAKVAKLNIQSLSPVKKKKMVPGALGVPADLAPVDVEFSFPKFSRLRRGLKAEAVKGPVPAAPARRRLQLPRLRVR', 'KGRSDEGRVRKVLK', 'KGVKRKADTTTP', 'KGVKRRADTTTP', 'KHKR', 'KHNRR', 'KIKELYRRR', 'KKAFQNVLRIQCLRRR', 'KKAKRKAREKQLEEARRLAALQKRRELRAAGIEIQKKRKKKRGVDYNAEIPFEKKPALGFYDTSEENYQALDADFRKLRQQDLDGELRSEKEGRDRKKDKQHLKRKK', 'KKAKRKAREKQLEEARRLAALQKRRELRAAGIEIQKKRKRKRGVDYNAEIPFEKKPALGFYDTSEENYQALDADFRKLRQQDLDGELRSEKEGRDRKKDKQHLKRKK', 'KKCSETWKTIFAKEKGKF', 'KKDPANTVEVKKGSRK', 'KKEIARQMKAYEKQRGTRREEQKE', 'KKERNSSGMARKAKRTK', 'KKERNSSGTTRKSKQTK', 'KKFGAQNVARRIEFRKK', 'KKFGPK', 'KKFKEEEASAKIPKKKR', 'KKGRGNRYHNKNRGKSK', 'KKGRRNRFK', 'KKHK', 'KKHLKIH', 'KKHVKTH', 'KKIKKKKKKKHR', 'KKKEKDICSSSKRRFQK', 'KKKK', 'KKKKGGGKKKK', 'KKKKK', 'KKKKKK', 'KKKKKSDKKKKKL', 'KKKKMTK', 'KKKKR', 'KKKKRK', 'KKKKRKK', 'KKKKSGQI', 'KKKKSKDKKRK', 'KKKLKK', 'KKKMKKHKNKSEAKKRKIEFLRPGYKAKRQKS', 'KKKNAKVVADIKKKRQRL', 'KKKNLPKFPKNKKKNGK', 'KKKNLQSQPNSTTSKKKH', 'KKKPAVCK', 'KKKPKK', 'KKKR', 'KKKRK', 'KKKRKR', 'KKKTEGLVKLTPIDKRK', 'KKKTGARKK', 'KKKTKK', 'KKLPPLPVVEKPKLFFKKR', 'KKLRP', 'KKLYQRKSKKSRHWKLK', 'KKLYQVKGKK', 'KKNKDKKRK', 'KKPKWDDFKKKKK', 'KKPR', 'KKPTWVCPVCDKK', 'KKQESNHMQISLCRKKV', 'KKQRLK', 'KKRETLPEKTARKKKRLK', 'KKRIR', 'KKRIRPLETTQQIRKRHC', 'KKRK', 'KKRKK', 'KKRKKD', 'KKRKLE', 'KKRKMTK', 'KKRKR', 'KKRP', 'KKRRK', 'KKRRKHKRR', 'KKRRKR', 'KKRSR', 'KKRTYISV', 'KKSFSTLFLETVKRK', 'KKSILKKKEQS', 'KKSRLKRRR', 'KKSSQSKKKKKAFSSQK', 'KKSSQTKKKKKAFNSPK', 'KKSSTRKDKEESKKKR', 'KKSYQDPEIIAHSRPRK', 'KKTGKNRKLKSKRVKPR', 'KKTGKNRKLKSKRVKTR', 'KKVSIAGQSGKLWRWKR', 'KKWK', 'KKYRGVRRR', 'KLGRRR', 'KLPIK', 'KLVPGLFKDEMKRRR', 'KLVPGLFKNEMKRRR', 'KLVPR', 'KLVTKLQNSERKKRGARR', 'KMISRKKKHQA', 'KPKKNKHD', 'KPRK', 'KPRKR', 'KPRRIRKPR', 'KPSKGQKRHLSTCDGQNPPKK', 'KPSLK', 'KQKQRFEEKRFK', 'KQRPRK', 'KRAADEVLAEAKKPR', 'KRANSNLVAAYEKAKKK', 'KRAR', 'KRARAC', 'KRASEDTTSGSPPKKSSAGPKR', 'KRCIWSTPKRRHKK', 'KRDVLDDLYRKLQR', 'KRFARGDKRGKLPR', 'KRGITNTLEESSSLKRK', 'KRGLNSSFETSPKKVK', 'KRGRKP', 'KRHR', 'KRIR', 'KRISDEKAFPLDGKRQR', 'KRIWNWRACEAAKKTKAD', 'KRKAKENIGKVNKKSNKKR', 'KRKCSQTQCPRKVIK', 'KRKEHPDS', 'KRKGKLKNKGSKRKK', 'KRKGPDPLSDGPVCKR', 'KRKGPDSLSDGPACKR', 'KRKGRAKGKGNKRKT', 'KRKH', 'KRKHVVK', 'KRKKGEKQAPGEEKGRKRRRVKEDKKKRDRDR', 'KRKKK', 'KRKKR', 'KRKKRRRQK', 'KRKL', 'KRKNEKAGSKRKK', 'KRKNSVEF', 'KRKNTKIISNMEKKRQRL', 'KRKPKEESEEGNSAESAAEERDQDKKRR', 'KRKPLP', 'KRKPQEESERAKSDESIKEEDKDQDEKRR', 'KRKQNQVD', 'KRKR', 'KRKRAV', 'KRKRGK', 'KRKRKTKA', 'KRKRMISN', 'KRKRPLLLNTNGAQKK', 'KRKRREK', 'KRKRRK', 'KRKVSSSKPEENKIR', 'KRKYR', 'KRLKRV', 'KRPASDMGKKPKTPKKKKKK', 'KRPKKRGRK', 'KRPR', 'KRPRK', 'KRQK', 'KRRHRSKVNGLQRGRKKD', 'KRRK', 'KRRKKK', 'KRRP', 'KRRR', 'KRRRQKIRKYTMRR', 'KRRRR', 'KRRRRRRREKRKR', 'KRRRTV', 'KRRS', 'KRRSK', 'KRRVVDEGEEADKAVKKKK', 'KRSESWTLKKPKSVSKKLK', 'KRSNDRTYSPEEEKQRRA', 'KRSR', 'KRSVVSFDKVKEPRKSRD', 'KRTSSPHKEESPKKTK', 'KRVK', 'KRVKPEEEEERDMKK', 'KRWQQRGRKANTRPLKRRRKRGPRI', 'KSGKAPRRRAVSMDNSNK', 'KTEEG', 'KVEKKK', 'KVKK', 'KVKTKKSTK', 'KYKEGK', 'KYRKNIWIKR', 'KYTKNKSNSFSQFVKK', 'LGEV', 'LGLPSEE', 'LGYKASTSLQDPLDKTGENKGWSGPKPGFPEPTNNTPKGI', 'LKKINGLL', 'LKKVKEHH', 'LKRKQVTA', 'LKRLAYAL', 'LKRLDAER', 'LRKRPRRD', 'LSPSLSPL', 'LTPRKKNKYRPISHTPS', 'MANKRMKVKH', 'MKRMGYNR', 'MQDPAAQS', 'MRRVESLE', 'NKKKKTRM', 'NRKGFVSS', 'NRKRKG', 'NRKRLKPG', 'NRKTTMLE', 'NYKRHMDGMYGPPAKRHEGD', 'NYKRPMDGTYGPPAKRHEGE', 'PAKRPR', 'PAPKKLKTS', 'PAPKKMKTS', 'PCKKSRK', 'PDKKRKE', 'PGGRGKKK', 'PGKMDKGEHRQERRDRPY', 'PGLTKRVKKSK', 'PGRKRKW', 'PIKKKRPPV', 'PKGRQRK', 'PKKACDRK', 'PKKAK', 'PKKFRFQ', 'PKKGDKYDKTD', 'PKKKKRKL', 'PKKKPAK', 'PKKKRHKV', 'PKKKRKKRSSKANK', 'PKKKRLR', 'PKKNKPE', 'PKKRKAP', 'PKKRKGR', 'PKKTQRR', 'PKPKKLKVE', 'PKPS', 'PKQAHR', 'PKRGRGR', 'PKRKRKRV', 'PKRKRRKKRGHGWSRMRMRR', 'PKRPR', 'PKRQRQRQ', 'PKRRK', 'PKRRRC', 'PKRTNVPG', 'PLERKKR', 'PLFKRR', 'PLGRRRV', 'PLRKAKR', 'PLRKRPRR', 'PLSKKRR', 'PNQKNRT', 'PPAKRKCIF', 'PPKKKRRV', 'PPKRKKRK', 'PPNKRMKVKH', 'PPPKDKKKKD', 'PPSKRPKA', 'PQKKVK', 'PRKKRGR', 'PRKRKG', 'PRKRP', 'PRRGKSPA', 'PRRIPRKI', 'PRRLRSPP', 'PRRRVQRKR', 'PRRVRLK', 'PRRYRSPP', 'PSAKRPK', 'PSRGRKR', 'PSRKRPR', 'PSTKKRE', 'PTKKRVK', 'PVKKSIR', 'PVKRRRM', 'PYFRKRM', 'QKGGRKK', 'QKKKRK', 'QKKLPKVK', 'QKRCKIVI', 'QKRKK', 'QKRTNVPG', 'QLQKP', 'QPKRP', 'QPQKKK', 'QPRRP', 'QRRTRKSQ', 'QRRTRKVA', 'QSGRSHSSGSSSSSSS', 'RAERKGKR', 'RARCRRHQRE', 'RDGFRRK', 'RGGRRRRRRRR', 'RGRPRKRQRL', 'RHKKK', 'RHREEHRRDR', 'RHRGRRR', 'RHRKIYTKKHH', 'RHRKRRR', 'RHRR', 'RKAEHWKHKKEESGRERKKNW', 'RKDPNNLSNQLETLTGSIRHRLK', 'RKDSKKKK', 'RKEKKRRRK', 'RKEKVKRE', 'RKFGPK', 'RKFHCWAPWQVVPKVRKD', 'RKFVAEYFAPNAKKR', 'RKIKLKRAK', 'RKIKRKRAK', 'RKKEAPGPREELRSRGR', 'RKKK', 'RKKKKK', 'RKKKKKTK', 'RKKQR', 'RKKR', 'RKKRK', 'RKKRR', 'RKKRRRRHRK', 'RKKSIPLSIKNLKRKHKRKKNKITR', 'RKKTDKLKKKKKRKRRDS', 'RKKVKP', 'RKLVKPKNTKMKTKLRTNPY', 'RKLVQIVEDQLCKKRLP', 'RKLYQVKGKK', 'RKNDAESKTGLDVSKKK', 'RKPLAGPKAAVLPPRPPTKRK', 'RKPVTAQERQREREEKRRRRQERAKEREKRRQERE', 'RKQLHQLLPSHVLQKKKK', 'RKRAAPEDFLGKGPNKK', 'RKRARAEKKALKKKKKI', 'RKRCVTAHWLNTVLKKKK', 'RKRGKPASGAGAGAGAGKRRRKADSAGDRGKSK', 'RKRGRNTK', 'RKRHW', 'RKRK', 'RKRKH', 'RKRKKMPASQRSKRRK', 'RKRKSRSRGDGTTVAERLKRWKEYNETVEEVSTKKRK', 'RKRLEHTERQFRNRRK', 'RKRLKSK', 'RKRQHIDD', 'RKRQRDD', 'RKRQTG', 'RKRR', 'RKRRK', 'RKRRR', 'RKRRRP', 'RKRRRR', 'RKRRSVSPDSDVTRRKK', 'RKRTPRVDGQTGENDMNKRRRK', 'RKSK', 'RKSTKKTNQSSKNIRKK', 'RKTKRK', 'RKVHECTASTKRRKKKKK', 'RLKAK', 'RMPKRQRIP', 'RNFHCWAPGKVVPKVRKD', 'RPRR', 'RPRRRSRR', 'RQQRKR', 'RRDLNSSFETSPKKVK', 'RREELAQIRKEEKEKKRR', 'RREFGDSKRVFGERRRN', 'RRGRKRKAEKQ', 'RRIQPAFGADHDVPKRKK', 'RRKKRR', 'RRKR', 'RRKRR', 'RRKRSKSEDMDNVQSKRRR', 'RRKRSKSEDMDSVESKRRR', 'RRKRSR', 'RRKSIKKKR', 'RRKSR', 'RRLGPTGKEVHALKRLRDS', 'RRLRI', 'RRMKWKK', 'RRNNKKRNREYYNYKRKA', 'RRRCLDFEMPGKRKK', 'RRRESLRI', 'RRRESYRQSDRDYHGEKRRR', 'RRRFK', 'RRRHK', 'RRRHSDENDGGQPHKRRK', 'RRRHSYENDGGQPHKRRK', 'RRRK', 'RRRKRR', 'RRRQLPPF', 'RRRR', 'RRRSPLPR', 'RRRTVQEARALLRCRRAG', 'RRSLRYSGDPGAKRSRNT', 'RRVKEEVLKLLPPKKDRI', 'RRVPQRKEVSRCRKCRK', 'RRVRQR', 'RRVRRK', 'RRVRVVPVKKQPQTKGKK', 'RRWNKLRLQDKEKRLK', 'RSKPKKKSKKHKDKE', 'RVVRRR', 'SANKVTKNKSNSSPYLNKRRGKPGPDS', 'SKKKSKR', 'SKKRKRPHCFETNPSVRKRQQNRLLRKLR', 'SKKSKSKR', 'SKKVTAKK', 'SKRKTKISRKTR', 'SKRRRRDE', 'SLGVRRR', 'SPQRP', 'SRKGGMTG', 'SRKKRAPHI', 'SRKLLELG', 'SRKLVSPE', 'SRRGRKKD', 'SRRMLSNR', 'SSRKR', 'TGKNEAKKRKIA', 'TKKQKAEK', 'TKKRERDE', 'TLRLKAK', 'VKKAHIET', 'VKRMLSNR', 'VRKKRKP', 'VRRARALE', 'VSGSKRRS', 'VSKKQRTGKKIH', 'WKKQLVAA', 'WRDASPP', 'WRKPEKEQ', 'YLRPVKKPKIRRKK', 'YRKLECLS']
# -----------------------------------------------------------------------------------------------------------
# Taken from http://web.expasy.org/protscale/pscale/Hphob.Doolittle.html
GRAVY_DIC = {
'A': 1.8, 
'R': -4.5,
'N': -3.5,
'D': -3.5,  
'C':  2.5,  
'Q': -3.5,  
'E': -3.5,  
'G': -0.4,  
'H': -3.2,  
'I':  4.5,  
'L':  3.8,  
'K': -3.9,  
'M':  1.9,  
'F':  2.8,  
'P': -1.6,  
'S': -0.8,  
'T': -0.7,  
'W': -0.9,  
'Y': -1.3,  
'V':  4.2}
# -----------------------------------------------------------------------------------------------------------
